# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3bb782a979a4bcc8d070b0647eb0231e3d76340c1af100a9d0403081562fef5e40bf46b875cd2a0661083f7e559f17c19b82acb95aa64020cd9a4fb2995b325e

test:
  secret_key_base: 0421da31b0c9c576b4fd2dadeb60384bef9b1a00fd5c5ddfc8df65d0d7fdef3c6a8121cbc89547bd6e0f507790a20d468040eb4ff107b960185894e3bcff35d1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
